#include "OPB_Int.h"

void disableAudioInterrupt(){
	Xint32 ier = XIntc_In32(XPAR_OPB_INTC_0_BASEADDR + XIN_IER_OFFSET);
//	XIntc_Out32(XPAR_OPB_INTC_0_BASEADDR + XIN_IER_OFFSET, (ier & ~XPAR_AUDIO_CODEC_INTERRUPT_MASK));
}

void enableAudioInterrupt(){
	Xint32 ier = XIntc_In32(XPAR_OPB_INTC_0_BASEADDR + XIN_IER_OFFSET);
//	XIntc_Out32(XPAR_OPB_INTC_0_BASEADDR + XIN_IER_OFFSET, (ier | XPAR_AUDIO_CODEC_INTERRUPT_MASK));
}

void acknowledgeAudioInterrupts(){
//	XIntc_Out32(XPAR_OPB_INTC_0_BASEADDR + XIN_IAR_OFFSET, XPAR_AUDIO_CODEC_INTERRUPT_MASK);
}

void clearInterrupts(){
	XIntc_Out32(XPAR_OPB_INTC_0_BASEADDR + XIN_MER_OFFSET, 0);
	XIntc_Out32(XPAR_OPB_INTC_0_BASEADDR + XIN_IER_OFFSET, 0);
	XIntc_Out32(XPAR_OPB_INTC_0_BASEADDR + XIN_IAR_OFFSET, 0xFFFFFFFF);
	//clear interrupts from ac97 slave
	//XIo_Out32(0x40080000 + 16, 0);
}

void initializeMER(){
	XIntc_Out32(XPAR_OPB_INTC_0_BASEADDR + XIN_MER_OFFSET, XIN_INT_MASTER_ENABLE_MASK | XIN_INT_HARDWARE_ENABLE_MASK);
}
